-- Carga inicial do quadro Scrumban (/admin/quadro).
-- Levantada a partir de TASK_PROGRESS.md, `gh pr list --state merged`,
-- docs/plano-grupos-campanhas-2026-08-10.md, docs/plano-implementacao-paginas-2026-08-11.md,
-- docs/handoff-pr3-auto-grow.md, docs/superpowers/{specs,plans}/*, docs/superpowers/plans/2026-07-29-automations-executor.md
-- e as pastas de rota apps/web/src/app/{painel,admin}.
--
-- Regra da carga: nada entra em 'no_ar_verificado'. Mesmo mergeado, mesmo no ar em produção,
-- sem prova colhida na hora o card nasce em 'no_ar_nao_verificado'.
--
-- Idempotente: reexecutar não duplica nem sobrescreve movimento manual (on conflict do nothing).
insert into public.board_features (key, title, area, status, summary, blocker, priority) values

  -- Grupos
  ('grupos-auto-grow', 'Auto-grow de grupos', 'Grupos', 'no_ar_nao_verificado',
   'Cria grupo novo quando o pool lota. Fila em Supabase.',
   'Nunca rodou com pool real: o gate honesto entrou no PR #90 e não foi exercitado.', 'alta'),
  ('grupos-invite-url', 'Link mestre de convite', 'Grupos', 'quebrado',
   'Link único que distribui entrada entre os grupos.',
   'Depende de invite_url, que o lojista não tem UI para preencher — só via PATCH /api/groups.', 'alta'),
  ('grupos-invite-backfill', 'Backfill automático de convite', 'Grupos', 'no_ar_nao_verificado',
   'Cron a cada 10min busca o código de convite via Evolution para grupos admin sem invite_url.',
   'PR #95 mergeado 12/08; ninguém checou os logs do cron em prod pra confirmar quantos dos 194 grupos foram preenchidos.', 'alta'),
  ('grupos-sync-evolution', 'Sincronização de grupos (Evolution)', 'Grupos', 'no_ar_nao_verificado',
   'POST /api/groups/sync busca grupos reais via Evolution API e preserva campos do painel.',
   'Produziu os 194 grupos em prod, mas ninguém confirmou com prova datada que o botão "Sincronizar" continua idempotente após os PRs #86/#90/#95.', 'media'),
  ('grupos-sync-legado-conflito', 'Sync legado conflita com o novo', 'Grupos', 'quebrado',
   'Endpoint POST /api/groups (engine legada) sincroniza grupos em paralelo ao sync novo.',
   'Reseta selected/engagement e força capacity de volta pra 1024 a cada rodada — dois caminhos com semânticas conflitantes, ambos vivos ao mesmo tempo.', 'media'),
  ('grupos-edicao-inline', 'Edição inline de convite/capacidade', 'Grupos', 'no_ar_nao_verificado',
   'Editar invite_url/capacidade direto na lista de grupos, com badge admin/não-admin.',
   'PATCH /api/groups não tinha nenhum chamador até o PR #86 ligar o fio; ninguém verificou salvando de verdade na UI em prod.', 'alta'),
  ('grupos-engajamento-real', 'Cálculo real de engajamento', 'Grupos', 'nao_existe',
   'Métrica de saúde do grupo calculada a partir de atividade real.',
   'groups.engagement nunca foi calculado (hardcoded "médio"); a UI que mostrava isso foi removida no PR #71 por ser dado fabricado e não foi substituída por cálculo real.', 'baixa'),

  -- Campanhas
  ('campanhas-wizard-presets', 'Wizard de campanha por objetivo', 'Campanhas', 'no_ar_nao_verificado',
   'Criar/editar campanha com passo "Objetivo", presets e mensagem sugerida.',
   'PR #33 mergeado 29/07; ninguém confirmou visualmente o fluxo completo depois das mudanças de sync/grupos de agosto.', 'media'),
  ('campanhas-ponte-broadcasts', 'Ponte de disparo pra broadcasts', 'Campanhas', 'no_ar_nao_verificado',
   'Ao criar mensagem na campanha, gera broadcast/schedule espelho que o motor real consome.',
   'Em 11/08 broadcasts e schedules tinham 0 linhas em prod — a ponte existe no código mas a máquina nunca foi exercitada de ponta a ponta.', 'alta'),
  ('campanhas-link-mestre-supabase', 'Link mestre /r/ no Supabase', 'Campanhas', 'no_ar_nao_verificado',
   'Resolve slug de campanha em campaign_groups/tracked_links, com rotação entre grupos e clique real.',
   'Confirmado 200 via curl isolado em 11/08 respondendo "empty-pool"; nenhuma campanha real com pool cheio testou a rotação nem o incremento de clique.', 'alta'),
  ('campanhas-atribuicao-vendas', 'Atribuição de R$ por campanha', 'Campanhas', 'no_ar_nao_verificado',
   'Vincula orders.campaign_id pra mostrar vendas atribuídas a cada campanha.',
   'PR #37 mergeado 29/07; depende de orders reais com campaign_id preenchido, que ninguém confirmou existir em prod.', 'media'),
  ('campanhas-cartao-compartilhavel', 'Cartão de resultado compartilhável', 'Campanhas', 'no_ar_nao_verificado',
   'Gera cartão de resultado + depoimento pra o lojista compartilhar.',
   'PR #38 mergeado 29/07; nunca visto gerado de verdade fora do ambiente de desenvolvimento.', 'baixa'),

  -- Disparos
  ('disparos-pagina-propria', 'Página própria de Disparos', 'Disparos', 'no_ar_nao_verificado',
   '/painel/disparos deixou de redirecionar pra campanhas e ganhou tela e entrada de nav própria.',
   'PR #79 mergeado 11/08; ninguém confirmou visualmente a tela nova em prod autenticado (o preview da Vercel não tem env de Supabase).', 'media'),
  ('disparos-biblioteca-composer', 'Biblioteca no composer de disparo', 'Disparos', 'no_ar_nao_verificado',
   'Composer de disparo puxa copies prontas da Biblioteca e marca marcos de funil.',
   'PR #80 mergeado 12/08; sem verificação visual registrada depois do merge.', 'baixa'),
  ('disparos-motor-worker-evolution', 'Motor de disparo (worker + Evolution)', 'Disparos', 'no_ar_nao_verificado',
   'Fila engine_commands → apps/worker → Evolution API, anti-ban no banco (8/min, 120/h, warmup até 800/dia).',
   'Rodando em DRY-RUN em prod (falta WORKER_SEND_ENABLED=true e envs Evolution no worker); broadcasts/schedules com 0 linhas em 11/08 — nunca mandou mensagem real.', 'alta'),
  ('disparos-motor-legado-baileys', 'Motor de disparo legado (Baileys)', 'Disparos', 'no_ar_nao_verificado',
   'Engine index.js faz poll 10s, claima broadcasts (run_id IS NULL) e dispara via anti-ban em RAM.',
   'É quem dispara de verdade hoje, mas nenhuma execução recente tem prova datada anexada nesta carga — só "funciona historicamente".', 'alta'),

  -- Automações
  ('automacoes-executor', 'Executor de automações', 'Automações', 'no_ar_nao_verificado',
   'Worker em apps/worker que dispara as automações do lojista.',
   'Vivo em produção e ocioso: zero automações ligadas, então nunca executou de verdade.', 'alta'),
  ('automacoes-triggers', 'Gatilhos de automação', 'Automações', 'no_ar_nao_verificado',
   'lead_entered, group_full, group_stalled e weekly_recurring criam runs automaticamente.',
   'Camada 2 entregue no PR #30; como nenhuma automação está ligada em prod (confirmado 11/08), nenhum gatilho jamais criou um run real.', 'alta'),
  ('automacoes-crud-templates', 'CRUD de automações + templates', 'Automações', 'no_ar_nao_verificado',
   'Criar/editar sequência de passos (wait/message/condition) a partir de templates prontos.',
   'Tela funciona e grava no banco, mas como o executor nunca rodou um run de verdade, nenhuma automação criada aqui foi confirmada end-to-end.', 'media'),
  ('squad-os-agentes-ia', 'Squad OS — equipe de agentes IA', 'Automações', 'em_construcao',
   'Squads, agentes, missões, decisões e handoffs com CRUD e realtime no painel.',
   'Não existe engine de execução: nada roda de fato os steps de uma missão — é estado (CRUD) sobre uma metáfora de equipe, sem worker que a anime.', 'baixa'),

  -- Páginas
  ('paginas-editor-lp', 'Editor de landing page (LP v2)', 'Páginas', 'no_ar_nao_verificado',
   'Criar/editar página de captação com blocos, preview ao vivo e publish/pause.',
   'Fases 2–5 no ar desde 17/07 atrás da flag NEXT_PUBLIC_LP_EDITOR_V2=on; sem reverificação visual desde então.', 'media'),
  ('paginas-tracking-captura', 'Tracking e captura de lead', 'Páginas', 'no_ar_nao_verificado',
   'Beacon de PageView/Lead/GroupJoin com consentimento LGPD, honeypot e dedup.',
   'Validado e2e numa sessão isolada em 02/07 (o próprio banco, sem carga real); nunca reconfirmado com tráfego de produção.', 'alta'),
  ('paginas-kit-divulgacao', 'Kit de divulgação (QR + WhatsApp)', 'Páginas', 'no_ar_nao_verificado',
   'QR code gerado localmente + compartilhar no WhatsApp + Páginas na nav mobile.',
   'PR #73 mergeado 12/08; ninguém confirmou o QR renderizando nem o navigator.share funcionando num celular real.', 'baixa'),
  ('paginas-duplicar-arquivar', 'Duplicar, arquivar e excluir página', 'Páginas', 'no_ar_nao_verificado',
   'Duplicar página com slug novo, arquivar sem perder métrica, excluir só sem captura.',
   'PR #75 mergeado 12/08; sem verificação visual registrada pós-merge.', 'baixa'),
  ('paginas-crm-integracao', 'Captura da LP alimenta o CRM', 'Páginas', 'nao_existe',
   'Lead capturado na página vira contato (leads) e é enriquecido quando entra no grupo.',
   'Planejado nas Fases 2 (D1A+D6A) do plano de 11/08; nenhum PR desse escopo apareceu na lista de mergeados até 12/08 — não implementado.', 'media'),
  ('paginas-funil-completo', 'Funil completo por página', 'Páginas', 'nao_existe',
   '6 degraus (view → form_start → lead → group_click → entrou no grupo) com quebra por device/UTM.',
   'Depende da integração com CRM (paginas-crm-integracao) que ainda não existe; planejado como Fase 3 do plano de 11/08.', 'baixa'),

  -- Auth
  ('auth-google-login', 'Login com Google', 'Auth', 'no_ar_nao_verificado',
   'OAuth client-side (auth-js flowType implicit) ligado nos dois Supabase.',
   'PR #84 mergeado 12/08; ninguém logou de verdade com uma conta Google em prod pra confirmar o vínculo de conta por e-mail.', 'media'),
  ('auth-login-resiliente-upstash', 'Login resiliente à queda do Upstash', 'Auth', 'no_ar_nao_verificado',
   'Rate limit falha aberta: Upstash fora do ar não derruba o login.',
   'PR #92 mergeado 12/08; só revisão de código — ninguém derrubou o Upstash de propósito pra confirmar que o login continua passando.', 'media'),
  ('auth-account-takeover-fixes', 'Correções de account takeover', 'Auth', 'no_ar_nao_verificado',
   'Fixes de takeover de conta e vazamento cross-tenant encontrados na auditoria de segurança.',
   'PRs #54/#57 mergeados 07/08; a auditoria (06/08) ainda lista H3 e L1–L9 pendentes, então a superfície completa nunca foi re-auditada depois do fix.', 'alta'),

  -- Admin
  ('admin-impersonation-fail-closed', 'Impersonation fail-closed', 'Admin', 'no_ar_nao_verificado',
   'Admin sem PLATFORM_ADMIN_EMAILS falha fechado; cookie de impersonation expira no servidor.',
   'PRs #92/#93 mergeados 12/08; ninguém testou o cenário de borda (env var ausente, saída de impersonation) em prod de propósito.', 'alta'),
  ('admin-funil-conversao', 'Funil de conversão (admin)', 'Admin', 'no_ar_nao_verificado',
   'Funil por etapa + taxas de conversão + ativação por tenant.',
   'PR #31 mergeado 29/07; instrumenta funnel_events, mas ninguém confirmou os números batendo com uso real recente.', 'media'),
  ('admin-agentes-ia', 'Painel de Agentes de IA', 'Admin', 'no_ar_nao_verificado',
   'Lista os 22 agentes especializados usados pela plataforma.',
   'Tela existe (admin/agentes); sem verificação de que os dados exibidos refletem os agentes realmente em uso em apps/web/src/lib/agents/.', 'baixa'),
  ('admin-saude-plataforma', 'Saúde da Plataforma', 'Admin', 'no_ar_nao_verificado',
   'Env vars, Stripe price IDs e problemas detectados automaticamente.',
   'Tela existe e roda checks; ninguém confirmou que os "problemas detectados" refletem o estado real de prod agora.', 'media'),
  ('admin-billing', 'Billing (admin)', 'Admin', 'no_ar_nao_verificado',
   'Invoices do Stripe + assinaturas do banco lado a lado.',
   'Tela existe; ninguém conferiu se invoice do Stripe e assinatura do banco batem pra um tenant real.', 'media'),

  -- Landing
  ('landing-girumo-v2', 'Landing "O Fluxo" (redesign v2)', 'Landing', 'no_ar_nao_verificado',
   'Redesign completo com GSAP, canvas de partículas e scrollytelling do mecanismo.',
   'Verificado em preview local em 02/07; sem reconfirmação depois do rebrand Girumo e do PR #56 (redesign com swap por breakpoint).', 'baixa'),
  ('landing-showcase-modelos', 'Showcase de modelos de LP', 'Landing', 'no_ar_nao_verificado',
   'Seção lp-showcase com 3 temas de marca trocáveis em frame de celular.',
   'Construído na iteração v2.1 (02/07); sem verificação depois do rebrand pra Girumo.', 'baixa'),
  ('landing-rebrand-girumo', 'Rebrand HubFlow → Girumo', 'Landing', 'no_ar_nao_verificado',
   'Landing, e-mails e shells trocados de marca, com brand:check no CI.',
   'PR #20 mergeado 17/07; brand:check permite propositalmente identificadores internos "hubflow" — ninguém auditou se algum vazou pra UI pública depois.', 'media'),

  -- Engine/Worker
  ('engine-evolution-migracao', 'Migração Baileys → Evolution API', 'Engine/Worker', 'no_ar_nao_verificado',
   'Troca do motor de WhatsApp (Baileys) pela Evolution API v2.3.7 hospedada no Coolify.',
   'Smoke test da F1 (26/07) só validou envio de texto simples (sendText); mídia/enquete nunca foram testadas contra a Evolution real.', 'alta'),
  ('engine-worker-anti-ban-banco', 'Anti-ban no banco (multi-réplica)', 'Engine/Worker', 'no_ar_nao_verificado',
   'Cota e estado de envio movidos pra Postgres (warmup, gate, breaker), substituindo o anti-ban em RAM.',
   'Validado só em Postgres descartável com smoke sintético; o checklist do F4 no TASK_PROGRESS ainda lista "smoke e2e (teste de fogo)" como pendente.', 'alta'),
  ('engine-watchdog-reconexao', 'Watchdog de reconexão', 'Engine/Worker', 'no_ar_nao_verificado',
   'Detecta e recupera socket zumbi (WhatsApp desconectado sem o engine perceber).',
   'PR #48 mergeado 30/07; nunca visto agindo sobre uma desconexão real em prod.', 'media'),
  ('engine-lead-capture-worker', 'Worker de captura de leads', 'Engine/Worker', 'no_ar_nao_verificado',
   'Consome group-participants.update e cria lead a cada entrada real em grupo.',
   '"Vivo em prod, 6 leads" é uma contagem de memória de sessão anterior, não uma verificação com prova datada nesta carga.', 'media'),

  -- Infra
  ('infra-csp-nonce', 'CSP com nonce por-request', 'Infra', 'no_ar_nao_verificado',
   'Content-Security-Policy com nonce dinâmico nas superfícies públicas.',
   'PR #59 (M5); cobre só /p/ e /r/ — as outras ~42 rotas viram HTML estático no build e não aceitam nonce, cobertura parcial por desenho.', 'media'),
  ('infra-rate-limit-upstash', 'Rate limiting distribuído (Upstash)', 'Infra', 'no_ar_nao_verificado',
   'Rate limit compartilhado entre instâncias via Upstash Redis, substituindo o limitador em memória.',
   'PR #55 (M3); Upstash foi provisionado pela integração da Vercel (12/08), mas ninguém forçou um cenário de estouro de limite em prod pra confirmar.', 'media'),
  ('infra-webhook-config', 'Configuração de webhook do WhatsApp', 'Infra', 'no_ar_nao_verificado',
   'Tela em Configurações pra o lojista configurar notificações/webhook.',
   'Sprint 4 item 17 do TASK_PROGRESS; tela existe (configuracoes/webhooks) mas nunca foi marcada como testada na checklist.', 'baixa'),
  ('infra-cutover-baileys-evolution', 'Cutover Baileys → Evolution', 'Infra', 'nao_existe',
   'Desligar o engine legado, remover rotas engine-only e o fallback JSON dual-mode (F5/F6).',
   'Decisão do Igor em 11/08: Baileys segue de pé por mais 1-2 meses — cutover explicitamente adiado, nenhuma das duas frentes começou.', 'media')

on conflict (key) do nothing;
